### Diversity and statistical analyses; carried out in R (version 3.5.2).

## Import data. Install and load required packages.
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("phyloseq")
library('phyloseq')
library('vegan')
library('ape')

## Import .shared file that contains OTU table generated by Mothur.
set.seed(336)
otus_16s <- import_mothur(mothur_shared_file="16S_WMP_OTU.shared")
otus_ITS <- import_mothur(mothur_shared_file="ITS_WMP_OTU.shared")

## Convert an object into a data frame and transpose the data.
otus_16s_dataframe <- as.data.frame(otus_16s)
otus_ITS_dataframe <- as.data.frame(otus_ITS)
otus_16s_t <- t(otus_16s_dataframe)
otus_ITS_t <- t(otus_ITS_dataframe)

## Create a phyloseq object.
OTU_16s = otu_table(otus_16s_t, taxa_are_rows=FALSE)
OTU_ITS = otu_table(otus_ITS_t, taxa_are_rows=FALSE)

taxon_16s <- import_mothur(mothur_constaxonomy_file="16S_WMP_TAX.taxonomy")
colnames(taxon_16s) <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus")
TAX_16s = tax_table(as.matrix(taxon_16s)) 

taxon_ITS <- import_mothur(mothur_constaxonomy_file="ITS_WMP_TAX.taxonomy")
TAX_ITS = tax_table(as.matrix(taxon_ITS))

metadat_16s <- read.table("Newmeta_pathogen.csv", sep=",", header=T, row.names=1)
metadat_16s$pos_s <- as.factor(metadat_16s$pos_s)
metadat_16s$pos_stec <- as.factor(metadat_16s$pos_stec)
metadat_16s$lm <- as.factor(metadat_16s$lm)
metadat_16s$ls <- as.factor(metadat_16s$ls)
META_16s = sample_data(metadat_16s)

metadat_ITS <- read.table("Newmeta_pathogen_ITS.csv", sep=",", header=T, row.names=1)
metadat_ITS$pos_s <- as.factor(metadat_ITS$pos_s)
metadat_ITS$pos_stec <- as.factor(metadat_ITS$pos_stec)
metadat_ITS$lm <- as.factor(metadat_ITS$lm)
metadat_ITS$ls <- as.factor(metadat_ITS$ls)
META_ITS = sample_data(metadat_ITS)

## Obtain phyloseq object for 16S rRNA.
phyloseq1 = phyloseq(OTU_16s,TAX_16s,META_16s)
TREE_16s = rtree(ntaxa(phyloseq1), rooted=TRUE, tip.label = taxa_names(phyloseq1))
phyloseq1 = phyloseq(OTU_16s,TAX_16s,META_16s, TREE_16s)
phyloseq1

library(dplyr)
phyloseq1 %>%
  subset_taxa(Domain == "Bacteria" & 
                Family != "mitochondria" & 
                Class != "Chloroplast") -> phyloseq1

phyloseq1

## Obtain phyloseq object for ITS.
phyloseq2 = phyloseq(OTU_ITS,TAX_ITS,META_ITS)
TREE_ITS = rtree(ntaxa(phyloseq2), rooted=TRUE, tip.label = taxa_names(phyloseq2))
phyloseq2 = phyloseq(OTU_ITS,TAX_ITS,META_ITS, TREE_ITS)
phyloseq2

phyloseq2 %>%
  subset_taxa(Rank1 == "k__Fungi" ) -> phyloseq2
phyloseq2

## Normalize OTUs using RLE method.
## Define a function for normalization.
## norm.edgeR
BiocManager::install("edgeR")
require(edgeR)
norm.edgeR =function(physeq, ...) {
  if (!taxa_are_rows(physeq)){ 
    physeq <- t(physeq)
  }
  x= as(otu_table(physeq), "matrix")
  x=x+1
  y=edgeR::DGEList(counts=x, remove.zeros=TRUE)
  z=edgeR::calcNormFactors(y, ...)
  return(z)
}
## Normalization.
otus_16s_edgeR <- norm.edgeR(OTU_16s, method="RLE")
otus_ITS_edgeR <- norm.edgeR(OTU_ITS, method="RLE")
  
OTU_16s_edgeR <- otu_table(otus_16s_edgeR$counts, taxa_are_rows = TRUE)
OTU_ITS_edgeR <- otu_table(otus_ITS_edgeR$counts, taxa_are_rows = TRUE)
  
phyloseq1_edgeR <- phyloseq(OTU_16s_edgeR, TAX_16s, TREE_16s, META_16s)
phyloseq1_edgeR
phyloseq2_edgeR <- phyloseq(OTU_ITS_edgeR, TAX_ITS, TREE_ITS, META_ITS)
phyloseq2_edgeR
  
## Transform OTUs into family level taxa.
phyloseq1_family_edgeR <- phyloseq1_edgeR %>%
tax_glom(taxrank = "Family")
phyloseq2_family_edgeR <- phyloseq2_edgeR %>%
tax_glom(taxrank = "Rank5")
  
phyloseq1_family <- phyloseq1_family_edgeR
phyloseq2_family <- phyloseq2_family_edgeR
